#!/bin/sh

case "$(uname -s | tr '[:upper:]' '[:lower:]')" in
  darwin)
    exec podman exec -i rocky8-x11 ~/projects/skill_sharp/bin/tcp_client -l SKILL $*
    ;;
  *)
    ~/projects/skill_sharp/bin/tcp_client -l SKILL $*
esac

